### ISSUE TITLE
能添加一个倒序下载/正序下载切换指令吗

### ISSUE THREAD

**Issue by bycen** [Jarvay/Pocket48-Review-Downloader#1]
或者是按时间段来下载视频，甚至自己选择一个个下都好。近期的回放都看了，硬盘不够大，不能从最新的开始下载

desktop48还更新吗，回放总是无法往前刷新，会卡住

**Comment by Jarvay** [comment]
是用的20220417这个版本吗，这个改成按时间倒序了（最新的回放在最前），想要逐个选择可以把config里的default_checked 改成false

**Comment by bycen** [comment]
多谢了，现在已经开始愉快的下载了

**Comment by bycen** [comment]
![Tu_2022-05-11_21-17-49](https://user-images.githubusercontent.com/41324481/167861131-864640f5-d1e8-4da7-8d6a-136f2e3cf12a.png)
这个下载失败重试次数显示的是直接新开了三个同时下载，但是重新下载完成后在临时文件夹里又没有多的片段，不知道是不是bug
